### ISSUE TITLE
Проблем с докер

### ISSUE THREAD

**Issue by baldzhiyski** [luchob/softuni-spring-may-2024#58]
*Връзка към проекта:*

https://github.com/baldzhiyski/Crossfit-Web-App/commit/d391506733392955f8811cb023757c6a63cbc6eb

*Кратко описание:*

Здравейте , направих всичко както Вие направихте във видеото , но не мога да си вдигна модулите с докер. Получавам много ексепшъни , едни и същи за всеки един от тях. Направил съм няколко скрииншота и също в последния ми къмит горе са всички промени , които съм направил. Прочетох неща и в интернет , но мисля , че само ме объркаха още повече. В момента съм махнал самите стойности на environment variablite  , но с тях също всичко гърми.
 
![Screenshot (102)](https://github.com/user-attachments/assets/67b6e1e3-c782-4e5b-b7a8-e1210fa27a4a)
![Screenshot (101)](https://github.com/user-attachments/assets/10dac585-edc1-4a1b-9f2e-f698b89bbe2d)
![Screenshot (100)](https://github.com/user-attachments/assets/e7e304db-9829-42f3-a976-b1fa904c4888)
![Screenshot (99)](https://github.com/user-attachments/assets/e9d572ff-be81-4157-8976-1bf3b9416f20)

**Comment by luchob** [comment]
Здравей! Съдейки по скриншотите, целият проблем е в това, че сървисите не могат да се свържат с ДБ-то. Самото ДБ изглежда работи. Нека да видим един примерен сетъп. В докер файла имаше нещо като:

```
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
``` 

Означава - пусни MySQL на 3306 и позволявай на root user-a да се връзва с празна парола. Правя го за удобство по време на девелопмънт иначе може да има и парола. Супер. Пусни го и опитай да се вържеш с някакъв туул, трябва да ти даде и да влезеш в ДБ.

После, да видим настройките в някой сървиз:

```
    password: ${my_pass}
    username: ${my_username}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/crossfit_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
```

За удобство и красота по време на локален дев може да ги направим и такива:

```
    password: ${MYSQL_PASS:}
    username: ${MYSQL_USER:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/crossfit_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
```

Накратко означава: ако няма env variables се вържи на localhost:3306 с user root и празна парола. Сега - env vars във docker-a:
```
  crossfit-trainings:
    depends_on:
      db:
        condition: service_healthy
    image: baldzhiyski/cross-trainings:v2
    ports:
      - "8081:8081"

    environment:
      - MYSQL_USER=root <--- дори в конкретния случай може и без него
      - MYSQL_HOST=db
      - MYSQL_PORT=3306 <--- дори в конкретния случай може и без него
```

Няма ли да стане така?

Поздрави,
Л.
